name: Flutter action
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2.12.0
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2.12.0
      with:
        channel: 'stable'
        flutter-version: '3.16.2'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build appbundle --release # or: flutter build apk --release
